version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 4000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - network
networks:
  network:
