version: "3.9"
services:
  frontend-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging

    container_name: frontend-staging
    restart: always
    ports:
      - 5555:3000
    networks:
      - network
networks:
  network:
