version: "3.9"
services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-dev
    restart: always
    ports:
      - 4000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - network
networks:
  network:
