FROM node:20-alpine AS builder
WORKDIR /app
COPY . .

RUN npm install
RUN npm run build -- --mode staging

FROM nginx:1.25.4-alpine-slim AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx-staging.conf  /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]